const numberOfQuestions = [
    {
        id: 0,
        question: "Question 1",
        questionNumber: "question1",
        radio: "radio1",
    },
    {
        id: 1,
        question: "Question 2",
        questionNumber: "question2",
        radio: "radio2",
    },
    {
        id: 2,
        question: "Question 3",
        questionNumber: "question3",
        radio: "radio3",
    },
    {
        id: 3,
        question: "Question 4",
        questionNumber: "question4",
        radio: "radio4",
    },
    {
        id: 4,
        question: "Question 5",
        questionNumber: "question5",
        radio: "radio5",
    },
    {
        id: 5,
        question: "Question 6",
        questionNumber: "question6",
        radio: "radio6",
    },
    {
        id: 6,
        question: "Question 7",
        questionNumber: "question7",
        radio: "radio7",
    },
    {
        id: 7,
        question: "Question 8",
        questionNumber: "question8",
        radio: "radio8",
    },
    {
        id: 8,
        question: "Question 9",
        questionNumber: "question9",
        radio: "radio9",
    },
    {
        id: 9,
        question: "Question 10",
        questionNumber: "question10",
        radio: "radio10",
    },
    {
        id: 10,
        question: "Question 11",
        questionNumber: "question11",
        radio: "radio11",
    },
    {
        id: 11,
        question: "Question 12",
        questionNumber: "question12",
        radio: "radio12",
    },
    {
        id: 12,
        question: "Question 13",
        questionNumber: "question13",
        radio: "radio13",
    },
    {
        id: 13,
        question: "Question 14",
        questionNumber: "question14",
        radio: "radio14",
    },
    {
        id: 14,
        question: "Question 15",
        questionNumber: "question15",
        radio: "radio15",
    },
    {
        id: 15,
        question: "Question 16",
        questionNumber: "question16",
        radio: "radio16",
    },
    {
        id: 16,
        question: "Question 17",
        questionNumber: "question17",
        radio: "radio17",
    },
    {
        id: 17,
        question: "Question 18",
        questionNumber: "question18",
        radio: "radio18",
    },
    {
        id: 18,
        question: "Question 19",
        questionNumber: "question19",
        radio: "radio19",
    },
    {
        id: 19,
        question: "Question 20",
        questionNumber: "question20",
        radio: "radio20",
    },
    {
        id: 20,
        question: "Question 21",
        questionNumber: "question21",
        radio: "radio21",
    },
    {
        id: 21,
        question: "Question 22",
        questionNumber: "question22",
        radio: "radio22",
    },
    {
        id: 22,
        question: "Question 23",
        questionNumber: "question23",
        radio: "radio23",
    },
    {
        id: 23,
        question: "Question 24",
        questionNumber: "question24",
        radio: "radio24",
    },
    {
        id: 24,
        question: "Question 25",
        questionNumber: "question25",
        radio: "radio25",
    },
    {
        id: 25,
        question: "Question 26",
        questionNumber: "question26",
        radio: "radio26",
    },
    {
        id: 26,
        question: "Question 27",
        questionNumber: "question27",
        radio: "radio27",
    },
    {
        id: 27,
        question: "Question 28",
        questionNumber: "question28",
        radio: "radio28",
    },
    {
        id: 28,
        question: "Question 29",
        questionNumber: "question29",
        radio: "radio29",
    },
    {
        id: 29,
        question: "Question 30",
        questionNumber: "question30",
        radio: "radio30",
    },
    {
        id: 30,
        question: "Question 31",
        questionNumber: "question31",
        radio: "radio31",
    },
    {
        id: 31,
        question: "Question 32",
        questionNumber: "question32",
        radio: "radio32",
    },
    {
        id: 32,
        question: "Question 33",
        questionNumber: "question33",
        radio: "radio33",
    },
    {
        id: 33,
        question: "Question 34",
        questionNumber: "question34",
        radio: "radio34",
    },
    {
        id: 34,
        question: "Question 35",
        questionNumber: "question35",
        radio: "radio35",
    },
    {
        id: 35,
        question: "Question 36",
        questionNumber: "question36",
        radio: "radio36",
    },
    {
        id: 36,
        question: "Question 37",
        questionNumber: "question37",
        radio: "radio37",
    },
    {
        id: 37,
        question: "Question 38",
        questionNumber: "question38",
        radio: "radio38",
    },
    {
        id: 38,
        question: "Question 39",
        questionNumber: "question39",
        radio: "radio39",
    },
    {
        id: 39,
        question: "Question 40",
        questionNumber: "question40",
        radio: "radio40",
    },
    {
        id: 40,
        question: "Question 41",
        questionNumber: "question41",
        radio: "radio41",
    },
    {
        id: 41,
        question: "Question 42",
        questionNumber: "question42",
        radio: "radio42",
    },
    {
        id: 42,
        question: "Question 43",
        questionNumber: "question43",
        radio: "radio43",
    },
    {
        id: 43,
        question: "Question 44",
        questionNumber: "question44",
        radio: "radio44",
    },
    {
        id: 44,
        question: "Question 45",
        questionNumber: "question45",
        radio: "radio45",
    },
    {
        id: 45,
        question: "Question 46",
        questionNumber: "question46",
        radio: "radio46",
    },
    {
        id: 46,
        question: "Question 47",
        questionNumber: "question47",
        radio: "radio47",
    },
    {
        id: 47,
        question: "Question 48",
        questionNumber: "question48",
        radio: "radio48",
    },
    {
        id: 48,
        question: "Question 49",
        questionNumber: "question49",
        radio: "radio49",
    },
    {
        id: 49,
        question: "Question 50",
        questionNumber: "question50",
        radio: "radio50",
    },
];

export default numberOfQuestions;
